// AUTO-GENERATED by scripts/gen-identity-core.mjs — do not edit by hand.
// Regenerate with: npm run gen:identity  (also runs at the start of npm run ingest)
export const IDENTITY_CORE = `Core facts about Ashim (authoritative, you always know these, no search needed):

Projects:
- GAN-Based Real-World Image Super-Resolution: A two-step GAN pipeline for real-world image super-resolution using a Real-to-Bicubic generator and nESRGAN+ network, achieving state-of-the-art perceptual quality. https://ashimsharma10.github.io/projects/gan-sr-pipeline
- PR Warden: A GitHub App that automatically triages pull requests using a multi-agent architecture: deterministic checks run alongside a tool-using LLM agent for deeper review. Posts a single verdict comment per PR with facet labels so maintainers route their queue without reading every diff. https://github.com/ashimsharma10/PR_warden
- Social Sentiment Dashboard: An event-driven sentiment monitor for Rivian: Reddit, App Store reviews, X/Twitter, and NHTSA complaints flow through a Kafka pipeline with HuggingFace sentiment analysis into a FastAPI + Next.js dashboard, backed by a Slack-integrated safety-triage queue. https://ashimsharma10.github.io/projects/social-sentiment-dashboard

Publication:
- Gaire R.R., Subedi R., Sharma A., Subedi S., Ghimire S.K., Shakya S. (2022) GAN-Based Two-Step Pipeline for Real-World Image Super-Resolution. ICT with Intelligent Applications. Smart Innovation, Systems and Technologies, vol 248. Springer, Singapore. https://link.springer.com/chapter/10.1007%2F978-981-16-4177-0_75

Experience: Data Scientist at Rivian & Volkswagen Group Technologies; Data Science & AI Teaching Assistant at CGI / University of Louisiana at Lafayette; Machine Learning Engineer at FuseMachines, Inc.

Contact: sharmaashim00@gmail.com · github.com/ashimsharma10 · www.linkedin.com/in/ashim-sharma-30a6aa349`
